language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH=$HOME/.yarn/bin:$PATH
node_js:
- '8'
- '9'
- '10'
cache: yarn
script: 
  - yarn lint
  - yarn build
  - yarn test
# deploy:
#   provider: npm
#   email: zephraph@gmail.com
#   api_key:
#     secure: 
#   on:
#     branch: master
#     tags: true
#     repo: zephraph/vue-graphql-loader
