language: node_js
node_js:
  - '8'
  - '9'
  - '10'
cache: yarn
script: 
  - yarn lint
  - yarn build
  - yarn test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
